### ISSUE TITLE
PancakeView in UWP ?

### ISSUE THREAD

**Issue by craigwi** [sthewissen/Xamarin.Forms.PancakeView#10]
I built some of this functionality with SkiaSharp, but would rather use this custom control.  My app runs on UWP too and would like to inquire about a UWP version of PancakeView.

**Comment by sthewissen** [comment]
Hey @craigwi - this is not planned from my end, but am certainly accepting PR's for it. No Windows machine here ;)

**Comment by craigwi** [comment]
There is some special handling of Frame and its content in UWP that I couldn't figure out (at least in Xamarin 3.5).  Instead, I solved this for UWP by subclassing Frame instead of ContentView and FrameRenderer instead of VisualElementRenderer.  

Then I ported PancakeViewRenderer for Droid and iOS to be a subclass of FrameRenderer -- and voila!

There are a few glitches to fix, but I'm well on my way.  Many thanks for solving the Droid and iOS parts of this!

**Comment by sthewissen** [comment]
Hey @craigwi, thanks for looking into it! Excited to see what you come up with. I redid some code on the iOS and Android side as well, so I'm curious regarding how that will function if it's changed into a FrameRenderer :)

**Comment by craigwi** [comment]
I have the latest PancakeView code.  The essential changes were to remove two duplicate properties (HasShadow and BorderColor) and rename CornerRadius to CornerRadii due to a conflict with Frame.

So far so good, but as noted there are some little issues (e.g., different arcs in background .vs. border) that I need to look at.  Also, a CornerRadius.TopLeft == 0 doesn't yield a sharp corner on at least iOS, but that may be a feature.

**Comment by craigwi** [comment]
The difference in arcs was on on iOS.  I fixed this by using the same UIBezierPath as in AddCornerRadius (with a call to ClosePath).

I also implemented BackgroundColor on iOS; not sure why that was missing.

I'll submit a PR soon.

**Comment by craigwi** [comment]
If you can tell me how to integrate the UWP renderer into the build, I can verify that it works.  I'm not familiar with those details.

**Comment by sthewissen** [comment]
It should be integrated already. Problem is that the build pipeline was setup in a way that it wouldn't allow external code to build on there (code in your repo). Would you mind closing the PR and re-opening a new one to verify that the changes I made were correct?

**Comment by sthewissen** [comment]
Also, I'm still not quite sure if switching to inheriting from `Frame` / `FrameRenderer` is preferred. At the very least it's something worth looking into further if it doesn't mess stuff up. Especially since it would introduce a breaking change (CornerRadius/CornerRadii) that will need to be checked. I plan on looking at the changes/running them locally in a bit.

**Comment by craigwi** [comment]
I look forward to trying out https://github.com/sthewissen/Xamarin.Forms.PancakeView/pull/49.  Many thanks!

**Comment by craigwi** [comment]
So far so good with 1.3.2-beta. The only issue I've run into is on iOS where if PancakeView has simple rounded corners and the sole content is a FFImageLoading.Forms.CachedImage, the image does not end up with rounded corners.  I had to put the CachedImage in a StackLayout to make this work.

This case is not an issue on UWP or Android.

**Comment by sthewissen** [comment]
Closing this for now. UWP support was added and I think individual issues should probably be reported as such :)
