### ISSUE TITLE
ColorTo animation does not work with BackgroundGradientStops

### ISSUE THREAD

**Issue by seansparkman** [sthewissen/Xamarin.Forms.PancakeView#101]
I was attempting to implement your last example from your [blog](https://www.thewissen.io/playing-with-animation-in-xamarin-forms/). I noticed that BackgroundGradientStartColor and BackgroundGradientEndColor are deprecated, so I was going to try to implement it using BackgroundGradientStops. We had been using BackgroundGradientStops for multiple colors anyway. However, I notice that updating the BackgroundGradientStops does not seem to be working or triggering the PropertyChanged event.

XAML:
```
   <yummy:PancakeView
        x:Name="Pancake"
        HorizontalOptions="FillAndExpand"
        VerticalOptions="FillAndExpand">
        <yummy:PancakeView.BackgroundGradientStops>
            <yummy:GradientStopCollection>
                <yummy:GradientStop Offset="0" Color="#8845b8" />
                <yummy:GradientStop Offset="0.3" Color="{StaticResource SecondaryColor}" />
                <yummy:GradientStop Offset="0.5" Color="{StaticResource SecondaryAccentColor}" />
                <yummy:GradientStop Offset="0.7" Color="{StaticResource SecondaryColor}" />
                <yummy:GradientStop Offset="1" Color="{StaticResource PrimaryAccentColor}" />
            </yummy:GradientStopCollection>
        </yummy:PancakeView.BackgroundGradientStops>
    </yummy:PancakeView>
```

Code Behind:
```
async void AddItem_Clicked(object sender, EventArgs e)
{
    var accentColor = Pancake.BackgroundGradientStops[0].Color;
    var secondaryAccentColor = (Color)App.Current.Resources["PrimaryDarkColor"];

    Pancake.PropertyChanged += Pancake_PropertyChanged;

    await Task.WhenAll(                
        Pancake.ColorTo(accentColor, secondaryAccentColor, c =>
        {
            var stops = Pancake.BackgroundGradientStops;
            stops[0].Color = c;
            Pancake.BackgroundGradientStops = stops;
            Debug.WriteLine($"Background Gradient {Pancake.BackgroundGradientStops[0].Color}");
        }, 5000, Easing.Linear)
    );

    Pancake.PropertyChanged -= Pancake_PropertyChanged;

    await DisplayAlert("Done", "Animation is done!", "OK");
}

private void Pancake_PropertyChanged(object sender, PropertyChangedEventArgs e)
{
    Debug.WriteLine($"Property Changed: {e.PropertyName}");
}
```

I see the debug messages and the alert just fine. It works fine when I use BackgroundGradientStartColor and BackgroundGradientEndColor. I see the property changed in the debug log when not using stops.

Code Behind:
```
async void AddItem_Clicked(object sender, EventArgs e)
{
    var accentColor = Pancake.BackgroundGradientStartColor;
    var secondaryAccentColor = (Color)App.Current.Resources["PrimaryDarkColor"];

    Pancake.PropertyChanged += Pancake_PropertyChanged;

    await Task.WhenAll(                
        Pancake.ColorTo(accentColor, secondaryAccentColor, c =>
        {
            Pancake.BackgroundGradientStartColor = c;
        }, 5000, Easing.Linear)
    );

    Pancake.PropertyChanged -= Pancake_PropertyChanged;

    await DisplayAlert("Done", "Animation is done!", "OK");
}

private void Pancake_PropertyChanged(object sender, PropertyChangedEventArgs e)
{
    Debug.WriteLine($"Property Changed: {e.PropertyName}");
}
```

XAML:
```
<yummy:PancakeView
    x:Name="Pancake"
    BackgroundGradientEndColor="#f52e33"
    BackgroundGradientStartColor="#8845b8"
    HorizontalOptions="FillAndExpand"
    VerticalOptions="FillAndExpand" />
```

Is this a bug or I am doing something wrong here?

**Comment by sthewissen** [comment]
Hey Sean, no you're not doing anything wrong. The deprecation message is in place to make those properties deprecated on vNext. Unfortunately like you said the `GradienStops` bits are indeed not bindable in the current release. That was also on the cards for vNext. I had hoped to get that pushed out sooner but I'm running into some issues with PropertyChanged not propagating upwards the way it should which I can't quite seem to figure out yet (from GradientStop > GradientStopCollection > BackgroundGradientStops to trigger a redraw on PancakeView level).

**Comment by seansparkman** [comment]
Would it work better if you used an ObservableCollection?

**Comment by sthewissen** [comment]
In vNext it should already be, but some of this propagation simply doesn't want to play nice. It works fine for background I think, but for borders it doesn't (yet).

https://github.com/sthewissen/Xamarin.Forms.PancakeView/blob/vnext/src/Xamarin.Forms.PancakeView.Multi/Platforms/Shared/GradientStopCollection.cs#L26

**Comment by sthewissen** [comment]
Propagation problems fixed. Look for this in vNext :)
