### ISSUE TITLE
Weird BorderThickness on Android 9.0 

### ISSUE THREAD

**Issue by TopSkillDeveloper** [sthewissen/Xamarin.Forms.PancakeView#105]
I set BorderThickness=4. On other versions of Android, the border looks normal (thin). At 9, it looks too thick. I Use Api 28.

**Expected behaviour:**
<a target="_blank" ><img src="https://d.radikal.ru/d16/2006/ea/baf765d83235.png" /></a>
**Actual behaviour:**
<a target="_blank" ><img src="https://d.radikal.ru/d20/2006/dc/c6b3b0b6b2c2.png" /></a>

**Comment by TopSkillDeveloper** [comment]
any thoughts on how to solve this issue?

**Comment by sthewissen** [comment]
Is this still happening in the 2.0 series of packages? It's seen a rework of the Android renderer, which took up some time and is why I haven't responded to this one earlier.

**Comment by TopSkillDeveloper** [comment]
since version 2, everything works, border is the same everywhere. The issue is resolved
