### ISSUE TITLE
Version 2.0.0.691, UWP will not build

### ISSUE THREAD

**Issue by Orgbrat** [sthewissen/Xamarin.Forms.PancakeView#109]
Updated to the new PancakeView 2.0.0.691 and Xamarain.Forms UWP project will not build. 

Errors:
Could not copy the file "C:\Users\orgbr\.nuget\packages\xamarin.forms.pancakeview\2.0.0.691\lib\uap10.0.16299\Xamarin.Forms.PancakeView\Xamarin.Forms.PancakeView.xr.xml" because it was not found.	
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4643	

Could not copy the file "C:\Users\orgbr\.nuget\packages\xamarin.forms.pancakeview\2.0.0.691\lib\uap10.0.16299\Xamarin.Forms.PancakeView\Microsoft.UI.Xaml\DensityStyles\Compact.xbf" because it was not found.	
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4643	

Performed Undo on all changes and rolled back to version 1.4.2 and everything builds again and works as it should.

Steve

**Comment by ttirrell** [comment]
I'm getting the same error

![image](https://user-images.githubusercontent.com/15491055/87261843-c8655500-c485-11ea-8f66-0d637a0bf5e2.png)

**Comment by sthewissen** [comment]
As is outlined on both [the wiki](https://github.com/sthewissen/Xamarin.Forms.PancakeView/wiki#a-quick-note-about-wpf--uwp) and [this accompanying blogpost for v2.0.](https://www.thewissen.io/pancakeview-goes-v2-0-heres-whats-new) the UWP version is not something I actively support. It was a community contribution when it was first introduced and I'm just not at home enough on the platform to support it myself. I will gladly prioritize the checking of PRs fixing breaking bugs in it and make sure they get merged quickly + get a new version out.

**Comment by Orgbrat** [comment]
Ok, thanks... Guess we are stuck on version 1.4.2 since right now it works perfectly.

**Comment by Agredo** [comment]
@Orgbrat you can try to copy and paste both files from an older folder C:\Users\UserName\.nuget\packages\xamarin.forms.pancakeview (Replace UserName)

**Comment by Orgbrat** [comment]
@Agredo  Even in the Xamarin.Forms.PancakeView version 1.4.2 that builds all projects (Droid, iOS and UWP) and works perfectly fine these two files do not exist in the nuget folder structure. Only file in each platform folder is the  Xamarin.Forms.PancakeView .dll except the uap 10.0.16299 folder which has the dll plus a Xamarin.Forms.PancakeView.pri file. 

Orgbrat

**Comment by EmilAlipiev** [comment]
latest version works for me

**Comment by Orgbrat** [comment]
@EmilAlipiev Well it seems that the latest version 2.0.1.698 has fixed the issue.
