### ISSUE TITLE
AndroidEnablePreloadAssemblies - Wrong colors

### ISSUE THREAD

**Issue by matteopiccioni** [sthewissen/Xamarin.Forms.PancakeView#11]
Hello,
in Xamarin.Android 9.2 release notes, Microsoft suggest to disable AndroidEnablePreloadAssemblies to have shorten startup times

In my case, if I edit my Android project adding

<PropertyGroup>
    <AndroidEnablePreloadAssemblies>false</AndroidEnablePreloadAssemblies>
</PropertyGroup>
as described [here](https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.2),
my PancakeView views are white or of wrong color.
Thanks

**Comment by sthewissen** [comment]
Do you have some more info for me? E.g. XamForms version, Android target version, support package versions etc? Or perhaps even a small sample project to reproduce? I tried adding this to the sample project, but it's still showing up as it should.

![image](https://user-images.githubusercontent.com/2419439/58436739-2d65bc00-80c7-11e9-931d-57834e62ba29.png)

**Comment by matteopiccioni** [comment]
Hello,
sure...sorry for lack of info.
Using your sample project I have no issues
In my project I have: 
- listview
- custom cells
- xf 4.0 

I modified [sample.zip](https://github.com/sthewissen/Xamarin.Forms.PancakeView/files/3226128/sample.zip),  a MS listview sample, and 'fortunately' the problem appear

Thanks for your help and for your great packages

**Comment by sthewissen** [comment]
This might be related to ListView caching. Try setting `CachingStrategy` to `RecycleElement`.

**Comment by matteopiccioni** [comment]
Unfortunately the problem appears also using RecycleElement,
and disappears removing AndroidEnablePreloadAssemblies.

Maybe setting 'AndroidEnablePreloadAssemblies' to false you should add library's initialize method for Android?

As  work around if I add an instantiate into OnCreate it works... 
```
       public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
	{
		protected override void OnCreate(Bundle bundle)
		{
			...
			global::Xamarin.Forms.Forms.Init(this, bundle);
                         new PancakeView();   // instantiate some PancakeView class
		}
	}
```

**Comment by sthewissen** [comment]
That suggests its an issue with the Linker. I could add an init method doing something similar in case this happens. What are the linker settings on your project?

**Comment by matteopiccioni** [comment]
In Debug: its set 'Not link'
In Release: 'Link only assembly SDK'
(translating from my ide language, so it could be slightly different)

I test app only in debug 
Thanks

**Comment by sthewissen** [comment]
@matteopiccioni `PancakeViewRenderer` has an Init method you could try using in your `MainActivity`. Let me know if that fixes things.

**Comment by matteopiccioni** [comment]
@sthewissen Thanks, it works
As soon as also #15 will be fixed, I'll can re-add Pancake to my project! 
Thanks a lot!
