### ISSUE TITLE
Shadows not rendered after upgrading to latest Xamarin 4.7

### ISSUE THREAD

**Issue by jihadkhawaja** [sthewissen/Xamarin.Forms.PancakeView#111]

**Comment by sthewissen** [comment]
I'm going to need some more info here. Platform, version of PancakeView, etc.

**Comment by sthewissen** [comment]
Upgraded the sample app and both iOS and Android shadows seem to work just fine 🤔

**Comment by johnbmangold** [comment]
I'm also seeing this issue so maybe i can fill in his missing details.
Xamarin.Forms 4.7.0.1080
Visual Studio 16.6.4
Xamarin.Android 10.3.1.4
Xamarin.iOS 13.18.2.1

Issue occurs when upgrading PancakeView to 2.0.0.691. Upgrading to 2.0.1.698 did not resolve the issue. Downgrading back to 1.4.2 fixed the issue. I'm seeing this on both Android and iOS.

Here are the settings I'm using for PancakeView:
```
<Style TargetType="views:PancakeView">
		<Setter Property="BackgroundColor" Value="White"/>
		<Setter Property="Padding" Value="5,10,5,10"/>
		<Setter Property="HasShadow" Value="True"/>
		<Setter Property="CornerRadius" Value="5"/>
</Style>
```

If you need anymore information or need me to answer anything, please let me know. Thank you for your time and for creating PancakeView. It's a great view.

**Comment by jihadkhawaja** [comment]
My issue was indeed when I upgraded the pancake package to v20, the  downgrade it again to 1.4 which fixed the issue, i noticed that backgroundAngleOffset disappeared from the newest version too which caused a lot of errors in my xaml code since i used it in some.

**Comment by Symorp** [comment]
Hello,
I also upgraded PancakeView to version 2.0.1.698. And `HasShadow` and `Elevation` are obsolete and not working. But when you use Shadow like this its working:
`
<pancakeview:PancakeView>
    <pancakeview:PancakeView.Shadow>
        <pancakeview:DropShadow BlurRadius="4" />
    </pancakeview:PancakeView.Shadow>
</pancakeview:PancakeView>
`
