### ISSUE TITLE
Why was BackgroundGradientAngle removed?

### ISSUE THREAD

**Issue by EmilAlipiev** [sthewissen/Xamarin.Forms.PancakeView#114]
why was the BackgroundGradientAngle removed? i thought that this is more known usage especially for those familiar with css. like you would do in this example https://www.w3schools.com/css/tryit.asp?filename=trycss3_gradient-linear_angles

I cannot find any example how to achieve this using **BackgroundGradientStartPoint** and **BackgroundGradientEndPoint**
 For example, how will you convert below angle to start end ?
```
<Setter Property="BackgroundGradientAngle"
                Value="315"/>

```
Can we extend wikipedia or release notes with such breaking changes?

**Comment by sthewissen** [comment]
The deprecation of this property has been described in the release notes:
https://github.com/sthewissen/Xamarin.Forms.PancakeView/releases/tag/v2.0.0.691

The fact that certain things have been reworked is the main reason that this is a new major version upgrade. Also, another reason to rework that API is that it is in line with the gradient work being done by the Xamarin.Forms team themselves:

https://twitter.com/davidortinau/status/1284593102263648259

![image](https://user-images.githubusercontent.com/2419439/87884731-c44eaf80-ca10-11ea-95ef-4bd98585cd11.png)

This makes the migration to the native stuff later easier and I like to be in line with the official stuff. Regarding how to use it, it's in line with what pretty much every platform natively uses:

https://medium.com/@arb1nsnmgl/playing-with-cagradientlayer-swift-3-0-6230b00054be
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.lineargradientbrush?view=winrt-19041

**Comment by sthewissen** [comment]
The complete removal of the `BackgroundGradientAngle` was accidental, it was meant to be around but not function anymore with an `[Obsolete]` tag applied to it. This is fixed in the newer beta versions.

**Comment by Alextorres950325** [comment]
what is the alternative, because use BackgroundGradientStartPoint  and BackgroundGradientEndPoint  doesn't have angle property
