### ISSUE TITLE
Pancake view doesnt appear on Android

### ISSUE THREAD

**Issue by AnthonyLatty** [sthewissen/Xamarin.Forms.PancakeView#12]
I imported all the necessary library components, but for some reason the pancake view doesnt show up on Android. On iOS it shows perfectly. Are there any additional setup that is required for Android?

>XAML
```
xmlns:yummy="clr-namespace:Xamarin.Forms.PancakeView;assembly=Xamarin.Forms.PancakeView"

<yummy:PancakeView HeightRequest="250"
                CornerRadius="0,0,0,70"
                 IsClippedToBounds="true"
                 HorizontalOptions="FillAndExpand">
                 <Image Aspect="AspectFill"
                        Source="bg_banner.png"
                        HorizontalOptions="FillAndExpand"
                        VerticalOptions="FillAndExpand" />
</yummy:PancakeView>
```

> MainActivity.cs

        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            Forms.Init(this, savedInstanceState);

            LoadApplication(new App());

            PancakeViewRenderer.Init();  // Initialize Pancake view
        }

**Comment by sthewissen** [comment]
There should not be any additional setup. Is the sample attached to this repo working for you?

**Comment by AnthonyLatty** [comment]
No, it returns `Error: Failed to resolve assembly: 'Xamarin.Forms.PancakeView, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`

**Comment by sthewissen** [comment]
Do you have some more info for me? E.g. XamForms version, Android target version, support package versions etc? Or perhaps even a small sample project to reproduce?

**Comment by AnthonyLatty** [comment]
My XF version is: 3.6.0.344457
My Android target version is : Android 9.0 (maximum) and Android 6.0 (minimum)

I tested this plugin on a fresh XF project and it works fine on both platforms, so it might be some error with my other packages.
