### ISSUE TITLE
Intellisense Issue with 2.0 inside of a collectionview/bindablelayout

### ISSUE THREAD

**Issue by jamesmontemagno** [sthewissen/Xamarin.Forms.PancakeView#121]
![image](https://user-images.githubusercontent.com/1676321/89694883-f09a7500-d8c6-11ea-9ee4-2c3d35f94739.png)

**Comment by sthewissen** [comment]
I'm on VSMac and have never seen this behavior before. `PancakeView` is but a humble `ContentView` in its inheritance chain, so I wonder what could be causing this.

**Comment by jamesmontemagno** [comment]
Hmmmm, I am noticing it in older versions as well. let me do some digging. I see it in itemtempalte as well for collectionview.

**Comment by jamesmontemagno** [comment]
I don't
