### ISSUE TITLE
Borders/corner radiuses not showing on iOS

### ISSUE THREAD

**Issue by ludas96** [sthewissen/Xamarin.Forms.PancakeView#122]
No CorderRadius, BorderColor or BorderThickness works while testing on iOS. 

 ```xaml
<pv:PancakeView CornerRadius="{Binding Source={x:Reference this}, Path=CornerRadius}"
                 BackgroundColor="{Binding Source={x:Reference this}, Path=BackgroundColor}"
                 Padding="{Binding Source={x:Reference this}, Path=Padding}">
    <pv:PancakeView.Border>
        <pv:Border Thickness="{Binding Source={x:Reference this}, Path=BorderThickness}"
                   Color="{Binding Source={x:Reference this}, Path=BorderColor}" />
    </pv:PancakeView.Border>

    ...

</pv:PancakeView>
```
Tested without bindings and the same issue occurs.

XF: 4.8.0
iOS: 13.5
PancakeView: 2.1.0 (updated to latest to see if it fixed the issue)

Works just fine on Android.

**Comment by sthewissen** [comment]
I have to admit that your bindings confuse me. What is `this`? What is it that you're referencing here?

**Comment by sthewissen** [comment]
Just updated the sample app to 4.8 which also uses bindings for these values. Borders work as designed there.

Could you verify that as well?

![image](https://user-images.githubusercontent.com/2419439/89811686-4d07c980-db3f-11ea-84a4-c8dbfe7c042d.png)

**Comment by ludas96** [comment]
> I have to admit that your bindings confuse me. What is `this`? What is it that you're referencing here?

It's just a name-attribute on the ContentView so I can reach the bindings for my custom control. This is working as intended :)

> Just updated the sample app to 4.8 which also uses bindings for these values. Borders work as designed there.
> 
> Could you verify that as well?
> 
> ![image](https://user-images.githubusercontent.com/2419439/89811686-4d07c980-db3f-11ea-84a4-c8dbfe7c042d.png)

Not sure what was going on, but using the Simulator on my MacBook, the problem was gone. I uninstalled the app from the iPad and now it works. Not sure what was going on, and the only problem now is that some borders are getting cut-off - this can be fixed by margin/padding on the parent though.
