### ISSUE TITLE
Make compatible with Android 10 / 11

### ISSUE THREAD

**Issue by aleksandrsmyk** [sthewissen/Xamarin.Forms.PancakeView#123]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Legacy.targets(5,5): Error XA2002: Can not resolve reference: `Xamarin.Android.Support.Compat`, referenced by `Xamarin.Forms.PancakeView`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.Compat`, or remove the reference to `Xamarin.Forms.PancakeView`. (XA2002)

**Comment by sthewissen** [comment]
Are you targeting AndroidX? If so, try using Android 9 as Target Framework to see if that fixes things.

**Comment by mikescandy** [comment]
my two cents. I had the same issue
- xamarin.forms 4.8.0.1269
- pancakeview 2.1.0.714
- android app targeting 10

I performed the migration of the android project to androidX and I got the same error.
Based on the instruction from the androidx migration package, I installed Xamarin.Android.Support.Compat and it builds.

I guess pancakeview will have to explicitly support androidx eventually?

**Comment by sthewissen** [comment]
Yeah, I'm fairly sure its related to that indeed. It's not supported yet atm.

**Comment by aleksandrsmyk** [comment]
> Are you targeting AndroidX? If so, try using Android 9 as Target Framework to see if that fixes things.

Yes, of course, we did migrate to AndroidX. Targeting Android 9 doesn't help. I did install Xamarin.Android.Support.Compat as well and it works, but I would like to avoid this extra package in the project.

**Comment by saamerm** [comment]
Hey Guys! I created a PR for this @sthewissen 
https://github.com/sthewissen/Xamarin.Forms.PancakeView/pull/130

**Comment by aleksandrsmyk** [comment]
We have already moved to Shapes -)

**Comment by sthewissen** [comment]
I won't be mad. Either way, this should be fixed in the v2.2.0.* beta.

**Comment by INHack20** [comment]
+1

**Comment by brminnick** [comment]
Hey Gang! 

It looks like including [Xamarin.Android.Support.v7.AppCompat v28.0.0.3](https://www.nuget.org/packages/Xamarin.Android.Support.v7.AppCompat/28.0.0.3) allows [PancakeView v2.1.0.714](https://www.nuget.org/packages/Xamarin.Forms.PancakeView/2.1.0.714) to work without issues with Android10.

I'm using `PancakeView v2.1.0.714` alongside `AndroidX` with `<TargetFrameworkVersion>v10.0</TargetFrameworkVersion>` without any issues in my GitTrends app: https://github.com/brminnick/GitTrends/blob/94b4f836369ebbcc18867a41a494766cffaee8c6/GitTrends.Android/GitTrends.Android.csproj#L87-L108

**Comment by saamerm** [comment]
@brminnick Yes i have seen it working for several people now. It seems like something inside the v2.1 package still needs AppCompat v28.

**Comment by sthewissen** [comment]
@brminnick @saamerm Added the package in #137. Should do the trick right?

**Comment by saamerm** [comment]
Yes, looks good to me
