### ISSUE TITLE
[Android]IndexOutOfBounds when using DashPattern

### ISSUE THREAD

**Issue by BaseCrusher** [sthewissen/Xamarin.Forms.PancakeView#125]
When you set the BorderMarkup DashPattern to anythink other then 0 when using Android a  Java.Lang.ArrayIndexOutOfBoundsException is thrown.

**Comment by sthewissen** [comment]
`DashPattern` is meant to be set to at least two values, seperated by a comma.

e.g. "10,4" would mean that the dash is 10 units wide and the space in between them is 4 units wide.

Setting it to a single value will indeed throw an error (because it won't work with a single value anyway), which I'm adding a check for.

**Comment by BaseCrusher** [comment]
Ahh all right. Thank you very much fpr the quick reply. :)

**Comment by BaseCrusher** [comment]
As a small edit. I would suggest setting the DashPattern with only one number would result that the dash length and the spacing are the value set in the DashPattern. On iOS this seams to work already.

**Comment by sthewissen** [comment]
This should be fixed in the current beta if you want to verify.

**Comment by BaseCrusher** [comment]
So I've taken a look it works just fine now. 👍 
If you'd like I can create a quick pull request for the documentations, so that users know that they can set the dash gap aswell if they'd like to. 
Only one thing that seamed a litle of, though it doesn't bug me, when I was using the Android version the dash gap was very small. I don't know why. Just wanted to let you know.

**Comment by sthewissen** [comment]
@BaseCrusher Thanks for the kind words, appreciate it. I'll happily take a docs PR :) I didn't even know that was possible for Wiki, so you learn something new every day. There is definitely a visual difference between Android and iOS for the dashes, but I haven't found the magic formula that makes the look in sync yet.

Regarding sponsoring, I don't quite know what people typically set up for that. I have the GH sponsors thing here, I have a Twitch stream where I guess one can throw bits at me. Other than that I don't know what people use these days. If you have suggestions I'll gladly take em.

**Comment by sthewissen** [comment]
Closing this since the original problem was solved.

**Comment by BaseCrusher** [comment]
@sthewissen I realized that I'm not able to do PR's to the wiki. So Im posting it here.

```
##Using Dash Pattern
The dash pattern takes two arguements. The first one is for the dash length and the second one for the dash gap. Setting only the first parameter results in the dash length and the dash gap to have the same value.
```

**Comment by sthewissen** [comment]
Thanks, I'll add a paragraph for it!
