### ISSUE TITLE
typo in wiki 

### ISSUE THREAD

**Issue by aktxyz** [sthewissen/Xamarin.Forms.PancakeView#128]
Hello and thanks for the great control !

https://github.com/sthewissen/Xamarin.Forms.PancakeView/wiki/Gradients

I think this ...

```<yummy:PancakeView BackgroundGradientStartPoint="0,0" BackgroundGradientStartPoint="1,0">```

should be this ...

```<yummy:PancakeView BackgroundGradientStartPoint="0,0" BackgroundGradientEndPoint="1,0">```

**Comment by sthewissen** [comment]
Thanks! 👍
