### ISSUE TITLE
Unable to render BackgroundGradient

### ISSUE THREAD

**Issue by novecento** [sthewissen/Xamarin.Forms.PancakeView#129]
Hi,
I started a new shared project from scratch, referenced this awesome project by nuget, and i try to do this:
`<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:yummy="clr-namespace:Xamarin.Forms.PancakeView;assembly=Xamarin.Forms.PancakeView"
			 x:Class="App4.MainPage">
	<ContentPage.Content>
		<StackLayout BackgroundColor="White">
			<yummy:PancakeView BackgroundGradientEndColor="Red"
							   BackgroundGradientStartColor="Gainsboro">
				<Label FontSize="20"
					   Text="PancakeView"
					   VerticalOptions="Center" />
			</yummy:PancakeView>
		</StackLayout>
	</ContentPage.Content>
</ContentPage>`

But I can't see any background on android. What is my mistake?

**Comment by novecento** [comment]
I don't have any problems with 1.6.x.

**Comment by sthewissen** [comment]
This is because those properties have been deprecated in v2.0 - use `BackgroundGradientStops` instead.

**Comment by sthewissen** [comment]
They will be completely removed in v2.1.
