### ISSUE TITLE
[Suggestion] Add shadowproperties to control

### ISSUE THREAD

**Issue by bentmar** [sthewissen/Xamarin.Forms.PancakeView#13]
Add the shadow properties as bindable properties.

**Comment by sthewissen** [comment]
Problem with this is that on Android the shadow is far less configurable than on iOS. Droid only let's you set elevation, which influences the radius/distance of the shadow. iOS supports different colors, offsets, radii etc. There's not really a lot of things shared between the two to abstract into a property.
