### ISSUE TITLE
VisualStateManager support

### ISSUE THREAD

**Issue by michelevirgilio** [sthewissen/Xamarin.Forms.PancakeView#139]
Hi, i would to know if PancakeView supports VisualStateManager: i've tried but "Selected" nor "Focused" status are not triggered.
Thanks

**Comment by sthewissen** [comment]
Unfortunately, there's no explicit code for that in place.

**Comment by michelevirgilio** [comment]
Thank you, maybe there is a simple way to accomplish my need: change the backgroundColor of the PancakeView when the user touch it?

**Comment by sthewissen** [comment]
Here's a blogpost on using PancakeView as a button. It scales on tap, which could be easily adapted into your scenario.

https://danielhindrikes.se/index.php/2020/07/14/building-a-styleable-content-button-with-pancakeview/

**Comment by michelevirgilio** [comment]
Thanks.
