### ISSUE TITLE
X.F. 4.0.0.471375 - No property, bindable property, or event found for...

### ISSUE THREAD

**Issue by matteopiccioni** [sthewissen/Xamarin.Forms.PancakeView#14]
After updating X.F. to 4.0.0.471375 version,
I have the following error using PancakeView on CornerRadius property:

No property, bindable property, or event found for 'CornerRadius', or mismatching type between value and property. 

The problem is on Android and iOS too

I have the same problem using your sample project and updating x.f. on each projects

**Comment by bcaceiro** [comment]
Happening the same to me.

**Comment by matteopiccioni** [comment]
On Twitter I read that latest Xamarin Forms  break something in several packages
David says that they are delisting the NuGet and they will push a corrected service release of Xamarin Forms :)

**Comment by matteopiccioni** [comment]
Fixed with latest xf update
