### ISSUE TITLE
[Regression] System.TypeLoadException: VTable setup of type Xamarin.Forms.PancakeView.PancakeView failed

### ISSUE THREAD

**Issue by brminnick** [sthewissen/Xamarin.Forms.PancakeView#141]
In `Xamarin.Forms.PancakeView v2.3.0.752-beta`, initializing an instance of PancakeView (e.g. `new PancakeView()`) throws a `System.TypeLoadException`:

> System.TypeLoadException: VTable setup of type Xamarin.Forms.PancakeView.PancakeView failed

### Reproduction Steps

1. Download/clone this repo: https://github.com/brminnick/PancakeViewRepro
2. In Visual Studio, open `PancakeViewRepro.sln`
3. In Visual Studio, set the Startup Project to `PancakeViewRepro.iOS`
4. In Visual Studio build/deploy `PancakeViewRepro.iOS` to an iOS device/simulator
5. Confirm `PancakeViewRepro.iOS` throws `System.TypeLoadException`
6. In Visual Studio, set the Startup Project to `PancakeViewRepro.Android`
7. In Visual Studio build/deploy `PancakeViewRepro.Android` to an Android device/simulator
8. Confirm `PancakeViewRepro.Android` throws `System.TypeLoadException`

### Workaround

Downgrade from v2.3.0.752-beta to v2.1.0.714

**Comment by sthewissen** [comment]
I'll happily remove the IBorderElement implementation, which is causing this. However, I've also recently removed some properties that were deprecated (and don't work anymore at this point). I feel like keeping these properties removed should not hurt. Try 2.3.0.754-beta.

**Comment by brminnick** [comment]
Great! I can confirm that I no longer get the `System.TypeLoadException` with 2.3.0.754-beta 🙌
