### ISSUE TITLE
How to retrieve the rendering given by HasShadow and Elevation?

### ISSUE THREAD

**Issue by Goldstrike** [sthewissen/Xamarin.Forms.PancakeView#142]
Hello,

I've launched a Xamarin.Forms [sample](https://github.com/Altevir/xamarinforms-covid19) that use `PancakeView` with elevation, but without shadow.

The style of the `PancakeView` is defined like this:

```
<Style x:Key="FrameTotal" TargetType="pancake:PancakeView">
    <Setter Property="BackgroundColor" Value="#FFFFFF" />
    <Setter Property="CornerRadius" Value="10" />
    <Setter Property="Elevation" Value="4" />
    <Setter Property="HasShadow" Value="False" />
    <Setter Property="Padding" Value="0" />
</Style>
```

Here is the default result [screenshot](https://i.ibb.co/h88pcMh/Simulator-Screen-Shot-i-Phone-11-2020-10-05-at-15-04-05.png): there is a light border and a very light shadow.

However, after having updated the packages `Xamarin.Forms` to 4.8.0.1451 and `Xamarin.Forms.PancakeView` to 2.1.0.714, the borders are no longer visible.

Here is the new result [screenshot](https://i.ibb.co/nMZ8bNv/Simulator-Screen-Shot-i-Phone-11-2020-10-05-at-15-37-08.png). The result is the same on iOS and Android.

I've tried to play with the `<Shadow/>`, but I didn't found how to reproduce the initial rendering. T
```
<pancake:PancakeView
    Grid.Row="1"
    Grid.Column="2"
    Style="{DynamicResource FrameTotal}">
    <pancake:PancakeView.Shadow>
        <pancake:DropShadow Offset="0,0" />
    </pancake:PancakeView.Shadow>
```
he shadow is bigger as we can see on this [screenshot](https://i.ibb.co/mJNNH8x/Simulator-Screen-Shot-i-Phone-11-2020-10-05-at-16-11-40.png).

**_Is there a way to retrieve the previous rendering with the latest packages?_**

**Comment by sthewissen** [comment]
The `HasShadow` and `Elevation` properties were deprecated in favor of using `Shadow`.

For iOS, the shadow from `HasShadow` was:

```
Radius = 10;
Color = Black;
Opacity = 0.4f;
Offset = 0,0;
```

If you used `Elevation`:

```
Radius = elevation;
Color = Black;
Opacity = 0.24f;
Offset = 0, elevation;
```

For Android, it pretty much comes down to `BlurRadius` = `Elevation`. Not sure if there's an easy way to reproduce what it was except for playing with the `BlurRadius`.

**Comment by Goldstrike** [comment]
Thanks for your feedback.

I've applied the values that you've given for `Elevation`, but I don't get the expected result, as we can see on this [screenshot](https://i.ibb.co/MGfkY5J/Simulator-Screen-Shot-i-Phone-11-2020-10-06-at-10-30-06.png).

So I will keep this approach, but it's too bad that we can't longer reproduce a "Material" rendering...

In add, is there a way to apply styles to `PancakeView.Shadow` and `PancakeView.Border`? I use PancakeView in different places, and it seems that I have to duplicate all this styles. This is a little tricky, as I need additionally to applied some values per platform (for the opacity for example).

**Comment by sthewissen** [comment]
I'm pretty sure that with some tinkering a similar result can be achieved. Regarding styling, yes, you can definitely set these in a style. Something along these lines should be possible:

```
<Style>
   <Setter Property="Shadow">
      <Setter.Value>
         <yummy:Shadow />
      </Setter.Value>
   </Setter>
</Style
```

Or alternatively:

```
<yummy:Shadow x:Key="SpecificShadowType" />
<Style TargetType="yummy:PancakeView">
    <Setter Property="Shadow" Value="{StaticResource SpecificShadowType}">
</Style>
```

Needs some more work, but you get the idea :)

**Comment by Goldstrike** [comment]
Hi @sthewissen, thanks again for your feedback.

Finally, I found a solution that satisfies me to have a Material rendering:

```
<yummy:PancakeView CornerRadius="8" BackgroundColor="White">
    <yummy:PancakeView.Shadow>
        <yummy:DropShadow Offset="1,2" Color="Black">
            <yummy:DropShadow.BlurRadius>
                <OnPlatform x:TypeArguments="x:Single">
                    <On Platform="Android" Value="2" />
                    <On Platform="iOS" Value="2" />
                </OnPlatform>
            </yummy:DropShadow.BlurRadius>
            <yummy:DropShadow.Opacity>
                <OnPlatform x:TypeArguments="x:Single">
                    <On Platform="Android" Value="1" />
                    <On Platform="iOS" Value="0.2" />
                </OnPlatform>
            </yummy:DropShadow.Opacity>
        </yummy:DropShadow>
    </yummy:PancakeView.Shadow>
</yummy:PancakeView>
```
However, I didn't yet found a way to apply the Shadow as a style.

I've created a new styles like this:

```
<Style x:Key="YummyShadowFrame" TargetType="yummy:DropShadow">
    <Setter Property="Offset" Value="1,2" />
    <Setter Property="Color" Value="Black" />
    <Setter Property="BlurRadius" Value="{OnPlatform Android=1, iOS=4}"/>
    <Setter Property="Opacity" Value="{OnPlatform Android=1, iOS=0.2}"/>
</Style>
<Style x:Key="YummyFrame" TargetType="yummy:PancakeView">
    <Setter Property="BackgroundColor" Value="White" />
    <Setter Property="CornerRadius" Value="8" />
    <Setter Property="Shadow" Value="{StaticResource YummyShadowFrame}" />
</Style>
```

But there is no way to apply the Shadow: only the PancakeView style is applied, not the DropShadow style...

**Comment by sthewissen** [comment]
Oddly enough, this version does seem to work:

```
            <Style x:Key="YummyFrame" TargetType="yummy:PancakeView">
                <Setter Property="BackgroundColor" Value="White" />
                <Setter Property="CornerRadius" Value="8" />
                <Setter Property="Shadow">
                    <yummy:DropShadow Offset="1,2" Color="Black"
                                      BlurRadius="{OnPlatform Android=1, iOS=4}"
                                      Opacity="{OnPlatform Android=1, iOS=0.2}" />
                </Setter>
            </Style>
```
Not quite sure why that would but the static resource route doesn't.

**Comment by Goldstrike** [comment]
@sthewissen yes you're right, thank you again!
