### ISSUE TITLE
.NET Core WPF and GTK

### ISSUE THREAD

**Issue by VladislavAntonyuk** [sthewissen/Xamarin.Forms.PancakeView#143]
It would be nice to add support for the same platforms as XF supports.

I see that mostly UWP and WPF are supported by community.
Are you ok with adding this new platforms? I can help you with it.

**Comment by sthewissen** [comment]
I'll happily take PRs for these. I can't support them myself due to time constraints.

**Comment by merryaiiit** [comment]
Does this support WPF and GTK or did it never happen? :)

**Comment by VladislavAntonyuk** [comment]
it is supported
