### ISSUE TITLE
iOS - Bindable property on BackgroundGradientStartColor BackgroundGradientEndColor doesnt update

### ISSUE THREAD

**Issue by matteopiccioni** [sthewissen/Xamarin.Forms.PancakeView#15]
Hello,
I try to bind BackgroundGradientStartColor and BackgroundGradientEndColor on my ViewModel, to change the Color runtime while some events occours.
In Android id works fine,
but in iOS the PancakeView doesn't change the colors.
I dont know if other properties have the same problem

Xamarin Forms 4.0 sr2
My PancakeView is in a ViewCell
All packages update to latest version.

Thanks

**Comment by matteopiccioni** [comment]
Hello,
trying to help in some way, I make a sample project
In this sample I make a listview with 3 cells.
In each cell there is a button. The button change the model property: StartColor, EndColor and BorderColor.

The results:
Android: all is working as expected
iOS: Only BorderColor change in the cells...background gradient color fails to change

Thanks!

[pankake.zip](https://github.com/sthewissen/Xamarin.Forms.PancakeView/files/3291214/pankake.zip)

**Comment by matteopiccioni** [comment]
Before using your PancakeView, I used one made by me
Now I am using PancakeView because is more complete comparing mine, but after finding this problem, I checked if it was present in my old renderer

Curiously it was also present, here's how I solved it:
Before InsertSublayer, i search and remove the existing one (if present):

```
            var gradLayer = Layer.Sublayers.Where(x => x.GetType() == typeof(CAGradientLayer)).FirstOrDefault();
            if (gradLayer != null)
                gradLayer.RemoveFromSuperLayer();

            NativeView.Layer.InsertSublayer(gradientLayer, 0);
```

I dont know if its the best way to do it

**Comment by sthewissen** [comment]
Seems like it could work. I'll try it out soon, or feel free to PR the change in :)

**Comment by matteopiccioni** [comment]
Sorry, I am not very practiced with github...
I made a clone of repository but the solution give me some compilation error
Maybe is better to wait for your update :)
Thank you

**Comment by sthewissen** [comment]
Try out 1.0.25-beta, it should solve this.

**Comment by matteopiccioni** [comment]
Unfortunately it still doesn't works
