### ISSUE TITLE
Found tag id where item is expected after updating from 2.1.0.714 to 2.3.0.759

### ISSUE THREAD

**Issue by arahmancsd** [sthewissen/Xamarin.Forms.PancakeView#153]
I am receiving "Found tag id where item is expected" when updating from 2.1.0.714 to 2.3.0.759. Clicking on the error points to a file "values.xml" which is auto generated by updating the package. The file contains the followings;

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <id name="view_tree_saved_state_registry_owner"/>
</resources>
```

Downgrading to 2.1.0.714 version executes without error.

**Comment by beeradmoore** [comment]
Hey @arahmancsd , this appears to be a duplicate of #131

**Comment by arahmancsd** [comment]
@beeradmoore yeah seems duplicate, but this isn't resolved yet. Cleaning and rebuilding doesn't solve the issue.

**Comment by agussaputrasijabat** [comment]
@arahmancsd Check the aapt2 checkbox in the project properties for your Android.
![Screenshot 2020-12-08 100312](https://user-images.githubusercontent.com/29218081/101433077-a1c81f00-393c-11eb-897f-3fcc9ac8029e.png)

**Comment by arahmancsd** [comment]
@agussaputrasijabat Thanks for the solution. This solved the issue.
