### ISSUE TITLE
Any way to add gradient stops?

### ISSUE THREAD

**Issue by adrianknight89** [sthewissen/Xamarin.Forms.PancakeView#17]
The current implementation seems to have a start and end color but nothing for intermediary colors. It'd be great to see an implementation similar to what I can do on [here](https://www.cssmatic.com/gradient-generator#'\-moz\-linear\-gradient\%28left\%2C\%20rgba\%28248\%2C80\%2C50\%2C1\%29\%200\%25\%2C\%20rgba\%28255\%2C255\%2C255\%2C1\%29\%2051\%25\%2C\%20rgba\%28231\%2C56\%2C39\%2C1\%29\%20100\%25\%29\%3B').

**Comment by sthewissen** [comment]
Currently there's no feature to do so. Also wondering how that would work in e.g. XAML. Would probably need to create a different type of object to handle these that takes a color and starting point into account. Might be worth exploring at some point.

**Comment by modplug** [comment]
Just a heads up on how it's done in WPF.

```
<!-- This rectangle is painted with a horizontal linear gradient. -->
<Rectangle Width="200" Height="100">
  <Rectangle.Fill>
    <LinearGradientBrush StartPoint="0,0.5" EndPoint="1,0.5">
      <GradientStop Color="Yellow" Offset="0.0" />
      <GradientStop Color="Red" Offset="0.25" />
      <GradientStop Color="Blue" Offset="0.75" />
      <GradientStop Color="LimeGreen" Offset="1.0" />
    </LinearGradientBrush>
  </Rectangle.Fill>
</Rectangle>
```

Maybe you can draw some inspiration from this :)

**Comment by sthewissen** [comment]
Implemented this in 1.0.25-beta. I did receive some comments regarding naming though. I have `Offset` named `Location` in mine. Not coming from a WPF/UWP world that made most sense to me. Also every platform names it differently:

iOS: Location
Android: Position
UWP: Offset

**Comment by adrianknight89** [comment]
I know that Forms tends to choose the naming in one platform when faced with a situation like that. It'd be fine if you chose `Offset` or `Stop`.

**Comment by sthewissen** [comment]
Will be in in the next release as `Offset`.
