### ISSUE TITLE
[Droid] Clipping using individual corner radii

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Xamarin.Forms.PancakeView#2]
Currently, clipping occurs using only one corner radius for all the corners. It would be nice if clipping can be done using the individual corner radii for each corner. This does work on iOS already, however it doesn't work on Android. The current `ViewOutlineProvider` doesn't seem to support it.

**Comment by modplug** [comment]
Doesn't FFImageLoading support this? https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Transformations.Droid/CornersTransformation.cs

**Comment by sthewissen** [comment]
We do something very similar when drawing the actual rounded corners on the background and the borders as what FFImageLoading is doing when drawing their images.

However, the difference is that FFImageLoading deals with an image, which isn't a content container and can't contain child controls. The problem we're running into is that `PancakeView` is a layout that can contain mone or ore layouts and controls which need to be clipped to the parent view (in this case the `PancakeView`). Drawing the corners works just fine, however if content exceeds these corners it will simply overlap them.

Hope that makes sense :)

**Comment by modplug** [comment]
It sure does. Thanks for the explanation 👍

**Comment by sthewissen** [comment]
This is fixed in the latest 1.24-beta release. Please feel free to experiment if you feel like it!
