### ISSUE TITLE
ios Gradient Repaint on rotate device

### ISSUE THREAD

**Issue by KKoustas** [sthewissen/Xamarin.Forms.PancakeView#24]
Hi,
I notice that in iOS devices if you add a pancake view with horizontal and verical option as fill and expande and set the BackgroundGradientStart/EndColor if the app start in verical orientation and then the user swithes to horizontal orientation the gradient does not fill the view.

You can check the attached demo app 
[App2.zip](https://github.com/sthewissen/Xamarin.Forms.PancakeView/files/3395969/App2.zip)

**Comment by sthewissen** [comment]
In the final position the gradient fills the screen for me, even in the sample you provided. Or do you mean during the rotation that there's a small red background visible in your sample? I wouldn't know how to fix that to be honest. That would mean redrawing during every frame of the rotation animation. Not even sure that can be done.

**Comment by sthewissen** [comment]
Closing due to being stale for months.
