### ISSUE TITLE
d: design time property support 

### ISSUE THREAD

**Issue by kmvickers** [sthewissen/Xamarin.Forms.PancakeView#27]
great control but doesnt seem to support design time properties even for simple properties like background colour or border color

**Comment by sthewissen** [comment]
Pushing a 1.1.6-beta version which has `[DesignTimeVisible(true)]` added as per:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/render-custom-controls#enable-design-time-rendering-for-custom-controls

I'm currently not able to see the Previewer at all in my VSMac Preview build. Still need to figure out what that is or switch back to the Stable branch, but that might take a while.

**Comment by sthewissen** [comment]
Implemented recently;

![image](https://user-images.githubusercontent.com/2419439/62831777-75a36d80-bc24-11e9-84d7-424b63d47e60.png)
