### ISSUE TITLE
Updating GradientStops dynamically

### ISSUE THREAD

**Issue by kphillpotts** [sthewissen/Xamarin.Forms.PancakeView#28]
I'm trying to do something pretty crazy where I update the GradientStops Offest property dynamically (a lot) as the application runs.  I also understand that this is probably not what they are designed to do ;-)  

Just updating the elements doesn't seem to work - I suspect this is because a GradientStop does not raise PropertyChanged, eg. this doesn't work:
`pancakeGradient.BackgroundGradientStops.ElementAt(1).Offset = (float)gradientSlider.Value;`

I can make it work by updating the whole collection because it's a bindable property, with some horrible code like this:
```
            var elements = pancakeGradient.BackgroundGradientStops.ToList();
            elements[1].Offset = (float)gradientSlider.Value;
            pancakeGradient.BackgroundGradientStops = elements;
```

When I do that, it works, but there is a memory leak (only tested on Android).  Seems that maybe there are a bunch of android bitmaps and PancakeDrawables hanging around. Here is a profiler view.

![image](https://user-images.githubusercontent.com/1327346/62180501-9d2c4780-b393-11e9-9275-5ae79164d437.png)

Anyway, Heaven forbid, I'm not suggesting this be fixed, just wondering if there is a recommended way I should be updating the GradientStops and then based on your feedback, happy to dig into the issue myself and try and work it out.

**Comment by sthewissen** [comment]
Hey Kym, you might be stretching this pancake too far sir! 😂

Joking aside, I'd love to help out in trying to fix what you're trying to do, but might be in need of some of your help as well :) Cleaning up those memory leaked pancakes sounds like something that should be fixable. Updating single stops' offset sounds like the GradientStop itself should also be popping some notifications to redraw the drawable. Not impossible, but could get tricky.

What is the functional requirement of what you're trying to achieve?

**Comment by kphillpotts** [comment]
Don’t worry there is no way I would expect you to work on this, it’s a pretty wacky requirement for the awesome Pancake. 

The requirement is just to animate gradients I’ve time. Normally I would just SkiaSharp it, but then remembered that Pancake supports gradient stops now. Which is why I thought I’d give it a little go. 

But really with this issue I just wanted to check I wasn’t doing something super-stupid. 

I’m more than happy to work on a pull request for this. Really, I think there are two issues:

1) investigate memory leaks in Android (haven’t checked iOS)
2) make GradientStops raise a PropertyChanged which would cause a redraw of the pancake. 

What do you think?

**Comment by sthewissen** [comment]
I think it sounds awesome! I figured it would be some animation type deal that you were trying to get going. I've been thinking about doing one for the EasyLoading package to fake a shimmer for a skeleton loader, but not necessarily through Pancake. I'd be curious to see how performance would be impacted 😂If you want to give it a go, certainly go for it. If you need anything from me I'd be happy to help.

P.S.
Pancake > Crepe.

**Comment by shanranm** [comment]
#32 removes unnecessary PancakeDrawable creation. Should probably address the memory leaks. Can someone checkout with profiler again?

**Comment by sthewissen** [comment]
If you simply want to animate an existing gradient to move along an axis we might be able to do that with a simple property, similar to the BackgroundGradientAngle property that we have now. Check out the debug app in #32 - If you play with the gradient angle in there I see some potential for animation if we can do a property that offsets/repeats the entire gradient over an axis.

**Comment by sthewissen** [comment]
@kphillpotts call me crazy, but I've actually started playing around with bindable colors.

**Comment by sthewissen** [comment]
All the work for this is done on the vnext branch ✅🎉

I don't have a specific release date for this yet. Been thinking of rewriting a lot of stuff, to be honest, to make it all a bit more consistent. I can pump out a beta release somewhere over the next few days though.
