### ISSUE TITLE
[iOS] Dashed border and corner radius don't play nice together

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Xamarin.Forms.PancakeView#3]
Currently the dashed border feature works for most cases, except for a weird behavior on iOS. As you can see in the screenshot below the border seems to be compressed forming a solid line. Initial thoughts are that the rounded corners are causing this. On Android this looks just fine.

![image](https://user-images.githubusercontent.com/2419439/52779618-d0c71f80-3048-11e9-8900-fd92411fb470.png)

**Comment by Miiite** [comment]
Apparently we should be using UIBezierPath.FromRoundRect to avoid this issue. But the method does not seem to support individual corners radius, only a global value for all corners:

https://stackoverflow.com/questions/22356821/how-to-create-rounded-corners-with-cashapelayer/22356822

**Comment by sthewissen** [comment]
Yeah, that's why I was messing with a custom path and adding arcs to it:

https://stackoverflow.com/questions/50797620/round-corners-with-different-radius

**Comment by lucidBrot** [comment]
Has this been fixed? (Or why is it closed?)

The Demo gif in the readme says you're currently only supporting solid borders. Is that still true?

**Comment by sthewissen** [comment]
Yes, it was fixed in #be500fd.
