### ISSUE TITLE
Feature Discussion - Regular Polygons

### ISSUE THREAD

**Issue by shanranm** [sthewissen/Xamarin.Forms.PancakeView#31]
Hi @sthewissen thank you for the awesome library.
This discussion is mainly for seeing if all the features of PancakeView can be extended to draw Polygons. (Which was the main reason for creating another library)

As apparent from the code base - the [Polygon Frame](https://github.com/shanranm/Xamarin.Forms.PolygonFrame) is entirely based on the earlier versions of PancakeView

Here are a few things that I feel  may need some more work for integrating them...

| Property Name | May be issue? |
| ------ | ------ |
| CornerRadius | Can only be one - for all the corners of the polygon |
| HasShadow | iOS works fine. Android can only support for 0 radius. Anything other that 0 makes the Polygon Concave |
| Sides | New property. Defaults to - 4. May be 0 for circle? |
| OffsetAngle | New property. Better naming? Used for the starting rotation angle |
| Gradient | You've already mentioned it should work. I'm still sceptical, will add samples just to be sure |

Lastly and the most important one - It is `Regular Polygon` so only squares!!
Please feel free to add anymore things that you think may not be straight forward.

**Comment by shanranm** [comment]
| Property Name | May be issue? |
| --------------- | -------------- |
| IsRegular | New Property that switches to regular polygon mode. Sides and OffsetAngle will come to effect when this is `True` |
| CornerRadius | Only TopLeft is considered when `IsRegular` is set |
| Gradient | You were right, it is working flawlessly! |
| HasShadow | Still issues exists for Android CornerRadius > 0 |

**Comment by sthewissen** [comment]
Closing this one as #32 has merged into master :)
