### ISSUE TITLE
[Droid] Improve rendering of background/border

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Xamarin.Forms.PancakeView#34]
![image](https://user-images.githubusercontent.com/2419439/63081456-efe53200-bf43-11e9-8fac-a6fb16f29376.png)

Leaving this here before I forget about it. The background is sort  of leaking underneath the border when `Sides` = 4. Might need to rewrite the path used for the `Sides` = 4 case. I believe @shanranm has some ideas about this as well :)

**Comment by shanranm** [comment]
I am on it, but this multi-targetting on mac is slowing me down! 😞

**Comment by sthewissen** [comment]
Yeah, once that is supported better life will be a lot easier :(

**Comment by sthewissen** [comment]
Support has arrived ☺️☺️☺️

**Comment by shanranm** [comment]
Finally, I can bare to see multi-target project on VSMac!!

Removed converting to pixels for sides != 4
I don't see leaking anymore. Please take a look.

If it still persists, I'm thinking of drawing the RouncRect using Arcs and Lines of Path.
