### ISSUE TITLE
How to add gradient from left to right not from top to bottom

### ISSUE THREAD

**Issue by sarthak199526** [sthewissen/Xamarin.Forms.PancakeView#38]
I need to achieve view like attached image. But gradient always takes place from top to bottom.But I need from left to right
![WpfColourSlider1](https://user-images.githubusercontent.com/47110100/64175912-f9debe80-ce79-11e9-917c-728b16bd4f73.jpg)

**Comment by sthewissen** [comment]
Use the `BackgroundGradientAngle` property. It takes values from 0-360 to rotate the gradient.
