### ISSUE TITLE
[Droid] Border thickness doesn't seem to match up with iOS

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Xamarin.Forms.PancakeView#4]
The same border thickness value on both platforms gives us a very different looking border. It looks like the Android border is drawn on the outside or on the edge of the control, whereas the one on iOS is drawn on the inside. Might need to figure out a way to draw the Android one on the inside too.

**iOS:**
![image](https://user-images.githubusercontent.com/2419439/52779846-40d5a580-3049-11e9-94b9-008b97a19eec.png)

**Droid:**
<img src="https://user-images.githubusercontent.com/2419439/52779882-58149300-3049-11e9-9896-740de9e4ff22.png" width="350px">

**Comment by Miiite** [comment]
When drawing the outline on Android, BorderThickness is used "as is", and not converted into pixels (based on the screen's dp), is there a reason to that ?

if the border thickness used is actually 

`var borderThickness = _convertToPixels(_pancake.BorderThickness);`

Then the result is slightly closer to iOS value (but cornerRadius are misplaced)

![screenshot 2019-02-14 at 16 04 19](https://user-images.githubusercontent.com/475526/52795585-60cd8f00-3072-11e9-86b1-26e20db7a1f0.png)

**Comment by sthewissen** [comment]
The main reason for that is that I'm more of an iOS minded developer than an Android guy 😂 So yeah, I guess some more convertToPixels magic could fix this one I suppose.
