### ISSUE TITLE
The shadow is truncated on Android

### ISSUE THREAD

**Issue by lsaudon** [sthewissen/Xamarin.Forms.PancakeView#54]
The shadow is truncated by the size of element on Android but not on iOS.

- Xamarin.Forms (4.2.0.815419)
- Xamarin.Forms.PancakeView (1.2.1)

```xml
<Grid Margin="16,0">
    <Grid.RowDefinitions>
        <RowDefinition />
        <RowDefinition />
        <RowDefinition />
    </Grid.RowDefinitions>
    <pancakeView:PancakeView Grid.Row="1"
                             HorizontalOptions="FillAndExpand"
                             VerticalOptions="FillAndExpand"
                             BackgroundColor="White"
                             Elevation="8" />
</Grid>
```

![Screenshot_20191002-101245](https://user-images.githubusercontent.com/25029876/66028463-73abab80-e4fd-11e9-8393-174c3636daf4.jpg)

![image](https://user-images.githubusercontent.com/25029876/66028431-64c4f900-e4fd-11e9-927f-91aff49f9fe3.png)

**Comment by sthewissen** [comment]
I'm pretty sure this has something to do with Elevation on Android. Using the sample below you see something similar:

```
    <Grid Margin="16,0">
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition />
            <RowDefinition />
        </Grid.RowDefinitions>
        <Frame Grid.Row="1"
                HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand"
                BackgroundColor="White"
                HasShadow="true" />
    </Grid>
```

![image](https://user-images.githubusercontent.com/2419439/66271036-c668c880-e859-11e9-8799-1e036c183ee0.png)

Making the `Margin` a `Padding` fixes things though.

![image](https://user-images.githubusercontent.com/2419439/66271057-f4e6a380-e859-11e9-98bc-3602eaa98157.png)
