### ISSUE TITLE
Pancake View getting distorted when a List View is pulled to refresh

### ISSUE THREAD

**Issue by jelmarose** [sthewissen/Xamarin.Forms.PancakeView#55]
I have several components above a List View contained in a rounded Pancake View that becomes oblong/oval when said list is pulled to refresh. How do I prevent this from happening?

Before the list is refreshed:
![crop1](https://user-images.githubusercontent.com/15888411/66098836-d02ec980-e5d6-11e9-9584-b88adf14c4a2.png)

After the list is refreshed:
![crop2](https://user-images.githubusercontent.com/15888411/66098866-ef2d5b80-e5d6-11e9-9c47-3b7a0a7ca02e.png)

**Comment by sthewissen** [comment]
Do you have a sample for this I could use?

**Comment by jelmarose** [comment]
Sorry for the late reply, I found that the distorting problem is from using a grid parent layout. I replicated the design on a new project and it's working just fine.
