### ISSUE TITLE
Shadow doesn't work on iOS 13.0 

### ISSUE THREAD

**Issue by sarthak199526** [sthewissen/Xamarin.Forms.PancakeView#58]
This is the code I am using 
<PanCakeView:PancakeView
                Grid.Row="0"
                Grid.Column="0"
                Padding="5"
                BackgroundColor="{StaticResource PrimaryColor}"
                CornerRadius="0"
                HasShadow="True"
                HorizontalOptions="FillAndExpand"
                IsClippedToBounds="true">

See attached image to see result 

![image](https://user-images.githubusercontent.com/47110100/66740030-ba9b8880-ee8f-11e9-8fbc-0df66389599d.png)

The white view is the pancake view which does not comes with an shadow

**Comment by sthewissen** [comment]
By adding `IsClippedToBounds=true` you're essentially clipping off the shadow since it's rendered outside of the element and thus clipped off. Try removing that.

**Comment by sarthak199526** [comment]
Yes It works :) I got confused since it was working on android with the same configurations. Sorry My bad :) . Really fan of yours work

**Comment by sthewissen** [comment]
Thanks :)

**Comment by kamalkumar1** [comment]
i am using this code shadow not displaying on ios 13
```
<yummy:PancakeView IsClippedToBounds="False"  Grid.Row="0"  Grid.ColumnSpan="2" HasShadow="True" CornerRadius="75" HorizontalOptions="Center"  VerticalOptions="Center" WidthRequest="150" HeightRequest="150">
   <Image Source="dummy"  Aspect="Fill"  HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" />
</yummy:PancakeView>

```
correct me if wrong
