### ISSUE TITLE
Clipping AND shadows, can it be done?

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Xamarin.Forms.PancakeView#6]
Currently, the corner radii are applied by clipping the view. This is necessary for content to respect these rounded corners. However, clipping means that any shadow you applied also gets clipped off because the shadow is applied outside of the control bounds. 

I'm open to suggestions on how this could be fixed. The inflexibility when it comes to shadows on Android has also tempted me to draw a custom shadow underneath the control, but I have yet to dive deeper into that topic.

**Comment by sthewissen** [comment]
Fixed on Android, however, it does not allow individual corner radii. This is a platform limitation at this point. `PancakeView` will use the top left coordinate of `CornerRadius` when `HasShadow` is set to true.

**Comment by ChasakisD** [comment]
@sthewissen While there is a platform limitation over here, you can actually hack it. ViewOutlineProvider is responsible for drawing the shadow and clipping the view. So, you can clip the children in DrawChild by specifying individual corner radii, and then set a convex path to ViewOutlineProvider's outline. By doing that, the ViewOutlineProvider will only draw the shadow (and do not clip the view), children will be clipped from DrawChild and the parent view will keep the shadow.

**Comment by sthewissen** [comment]
@ChasakisD Ok, that sounds hacky but if it works... Would you be willing to whip up a PR for that? I'm currently somewhat busy messing with iOS getting all these parts to work together nicely 😂

**Comment by sthewissen** [comment]
This will be fixed on #32.
