### ISSUE TITLE
Hot Reload kills the frame

### ISSUE THREAD

**Issue by mharrisonbit** [sthewissen/Xamarin.Forms.PancakeView#63]
When using pancake views on a physical device and hot reload the frame is removed. This is only an issue on a physical iOS device with hot reload.

![Screen Shot 2019-11-05 at 1 10 29 PM](https://user-images.githubusercontent.com/11961531/68233925-32139200-ffce-11e9-8bd0-710f2a8dd423.png)
![Screen Shot 2019-11-05 at 1 13 45 PM](https://user-images.githubusercontent.com/11961531/68233957-4192db00-ffce-11e9-925c-e1cc64a99665.png)

**Comment by mharrisonbit** [comment]
I tried with the lastest stable release(1.3.5) and still have the same issue.

**Comment by joseBarreto** [comment]
> I tried with the latest stable release(1.3.5) and still have the same issue.

I am also getting errors on Android.
After pressing "Ctrl + S" a few times, the application is closed for excess memory.

**Comment by mharrisonbit** [comment]
I am running version 1.3.7 and I updated VS mac yesterday to 8.4 and pancake view seems to be working correctly now.

**Comment by sthewissen** [comment]
1.3.7 saw #62 get reverted. Might’ve been the cause of your issue as well? Glad it’s fixed now though!

**Comment by mharrisonbit** [comment]
So am I, thanks again for the work you do.
