### ISSUE TITLE
View Dissappear on returning to page on iOS

### ISSUE THREAD

**Issue by LeoJHarris** [sthewissen/Xamarin.Forms.PancakeView#67]
Hi there, 

I noticed an issue/bug on iOS that when returning to a page on iOS the pancakeviews are dissapeared, android seems okay but just affecting on iOS.

My setup is using FreshMvvm framework with side menu drawer, when I tap menu item in drawer and page appears with pancake views fine but on returning to the page again they are gone.

I think starteded happening on version 1.3.6

**Comment by matteopiccioni** [comment]
I think to have the same issue, v 1.3.6

**Comment by DiogoMartinh0** [comment]
I've got the same issue but with v1.3.5
v1.3.3 seems to work.

Maybe this is caused by https://github.com/sthewissen/Xamarin.Forms.PancakeView/pull/62

**Comment by sthewissen** [comment]
If someone has a fix, please PR it in. I'm currently unable to and will be for a while.

**Comment by LeoJHarris** [comment]
@DiogoMartinh0 1.3.4 works correctly. I tested.

**Comment by sthewissen** [comment]
@cryophobia Any thoughts on this? It might have to do with your most recent PR.

**Comment by cryophobia** [comment]
Hi @sthewissen - I can have a look at the issue. 

@LeoJHarris - do have a sample project for me to debug against?

**Comment by LeoJHarris** [comment]
[PancakeViewSample.zip](https://github.com/sthewissen/Xamarin.Forms.PancakeView/files/3899772/PancakeViewSample.zip)

I chucked a pancake view on the about page, navigate away and back again and youl notice it dissapears. I ran on a emulator

**Comment by cryophobia** [comment]
Hi @sthewissen - can confirm that PR #62 is the cause. I think the safest option is to roll back the PR until I can figure out another way to fix duplicate items in collection views.

**Comment by Carl-Wen** [comment]
Same issue in listview.

**Comment by sthewissen** [comment]
I undid #62 for 1.3.7 as suggested by @cryophobia.
