### ISSUE TITLE
[Feature] Add Shadows to UWP

### ISSUE THREAD

**Issue by RyanGaudion** [sthewissen/Xamarin.Forms.PancakeView#71]
I know it probably isn't easy to do but it's worth asking what is stopping this from happening?

**Comment by sthewissen** [comment]
Me not having a Windows machine mostly 😅

**Comment by RyanGaudion** [comment]
> Me not having a Windows machine mostly 😅

Fair enough! Is this likely to change, as it's the main reason I can't use PancakeView in my projects?

**Comment by sthewissen** [comment]
This is in 1.4.1 in a basic form.
