### ISSUE TITLE
[Feature] Multiple shadows

### ISSUE THREAD

**Issue by nor0x** [sthewissen/Xamarin.Forms.PancakeView#77]
i recently came across some ui elements where multiple shadows are used, especially in neumorphism designs like the one below
![image](https://user-images.githubusercontent.com/3210391/74593334-644f7980-502a-11ea-8d31-618f3e92afa4.png)

i'm a big fan of PancakeView and wanted to ask if such a functionality is planned? I think #74 could also be important for designs with multiple shadows.

Thanks

**Comment by sthewissen** [comment]
As much as this is possible on iOS, there's no decent way to implement this on Android as far as I can find. Since I want to keep the package as cross-platform as possible I have no immediate plans to implement it for just iOS.

**Comment by nor0x** [comment]
thanks for the info 👍 I know gradients on Android can be messy. I will look into this and how SkiaSharp can help me, but in a different repo because that's would be quite a dependency for PancakeView. Should i leave this open?

**Comment by sthewissen** [comment]
We can leave the feature open for all I'm concerned. However, it probably will not happen or have a very low priority :)

**Comment by themronion** [comment]
And again, you can grab ideas [here](https://github.com/roubachof/Sharpnado.Shadows/tree/master/Shadows)

**Comment by sthewissen** [comment]
This will not make its way into PancakeView any time soon. For all your shadowing needs I would suggest using Sharpnado:

https://www.sharpnado.com/sharpnado-shadows-add-many-shadows-to-any-xamarin-forms-view/
