### ISSUE TITLE
Borders not appearing properly in XF.CollectionView on IOS

### ISSUE THREAD

**Issue by naweed** [sthewissen/Xamarin.Forms.PancakeView#78]
Hi,

I am facing a strange issue. On iOS, the borders are behaving very strangely inside the collecitonview, but on Android, it works fine. Here is the code that I am using. I am also attaching the screenshot from physical iPhone device. Any idea, if I am doing anything wrong. To re-emphasize, it is working fine on Android.

            <CollectionView
                Grid.Row="1"
                SelectionMode="None"
                Margin="8"
                ItemsSource="{Binding Comments, Mode=OneWay}"
                ItemSizingStrategy="MeasureAllItems">

                <CollectionView.ItemsLayout>
                    <LinearItemsLayout Orientation="Vertical" ItemSpacing="14" />
                </CollectionView.ItemsLayout>

                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <pancakeview:PancakeView
                            Padding="0"
                            VerticalOptions="FillAndExpand"
                            HorizontalOptions="Fill"
                            CornerRadius="4"
                            BorderThickness="1"
                            BorderColor="{StaticResource BorderColor}"                            
                            Margin="2">

                            <Grid
                                Padding="8"
                                BackgroundColor="Transparent">

                                <Grid.RowDefinitions>
                                    <RowDefinition Height="26" />
                                    <RowDefinition Height="22" />
                                    <RowDefinition Height="Auto" />
                                    <RowDefinition Height="24" />
                                </Grid.RowDefinitions>

                                

                            </Grid>

                        </pancakeview:PancakeView>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>

![Screenshot 2020-02-20 at 17 26 59](https://user-images.githubusercontent.com/103980/74944949-f0391b00-5407-11ea-8e10-f1292e95b1e4.png)

Regards
Naweed

**Comment by sthewissen** [comment]
I'm aware of this as it is similar to #53, but I have no idea where it's coming from and how to fix it. A workaround that I've seen work in some scenarios is to not have PancakeView be the root element in the `CollectionView` `DataTemplate` but instead wrap it in a `StackLayout`.

**Comment by naweed** [comment]
Putting it inside ContentView solves it partially. I am now only left with issue of right-side border not showing properly.

Any help?

Regards
Naweed

![Screenshot 2020-02-24 at 13 57 17](https://user-images.githubusercontent.com/103980/75148717-5cba5f80-5711-11ea-97f5-fe34bb24f634.png)

**Comment by naweed** [comment]
Btw, adding a Padding of 2px to the ContentView has resolved the issue for me for now.

So, we can close this ticket, but need to identify and find a permanent fix.

Thanks for the great library though.

Regards
Naweed
