### ISSUE TITLE
BorderIsDashed looks bad on Android

### ISSUE THREAD

**Issue by Mikilll94** [sthewissen/Xamarin.Forms.PancakeView#81]
Here is how `BorderIsDashed` looks on iOS:

![image](https://user-images.githubusercontent.com/17653648/77161859-f4aa2f80-6aaa-11ea-836f-e444bf19481d.png)

And here is Android:

![image](https://user-images.githubusercontent.com/17653648/77162010-418e0600-6aab-11ea-89f7-a14ced3824b0.png)

As you can see on Android it looks bad. The dashes are barely visible.

Here is the repro project:
[pancaketest.zip](https://github.com/sthewissen/Xamarin.Forms.PancakeView/files/4359378/pancaketest.zip)

**Comment by sthewissen** [comment]
I will be adding a `BorderDashPattern` property that will let you tweak these borders further. That way you could give them separate values per platform to make it look the same. The way these dashes are done per platform makes it hard to convert one set of values to something that looks the same on each platform.
