### ISSUE TITLE
IOS tap gesture FAILS on latest IOS OS and Mac OSX

### ISSUE THREAD

**Issue by marcusts** [sthewissen/Xamarin.Forms.PancakeView#83]
This control worked perfectly for me until March, 2020.

I began having trouble running and debugging with my Phone, so updated OSX (10.15.4) and IOS (13.4).  My coding environments all changed as well. The Mac build server is now on 13.16.0.11 and 6.16.0.11.

The problem is that the pancake view no longer responds to taps. Android works fine.  The code is unchanged from a month ago.

I have monkeyed around with InputTransparent, but the fact that Android works indicates that something fundamental changed in these last Apple releases.

Can you have a look?  Just add a tap gesture recognizer to a pancake view, build & run with Apple's latest, and see what happens.

Thank you!

**Comment by sthewissen** [comment]
Unfortunately this is not an issue in PancakeView but on a higher level. You can read more about it here: https://github.com/xamarin/Xamarin.Forms/issues/10162

Hope that helps!

**Comment by marcusts** [comment]
Hi Steven,

Thanks, IOS is not currently connecting except with a yellow flag, but
cleary tha is not your fault.  I appreciate the clarification.

On the Android side, this error has popped up:



*Severity Code Description Project File Line Suppression StateError Can not
resolve reference: `Xamarin.Android.Support.Compat`, referenced by
`Xamarin.Forms.PancakeView`. Please add a NuGet package or assembly
reference for `Xamarin.Android.Support.Compat`, or remove the reference to
`Xamarin.Forms.PancakeView`. VDT.Mobile.Android   *

I don't declare the Pancake view under Android currently.  I just include
it in my Forms project.

Stephen

**Comment by sthewissen** [comment]
Please try installing it on each platform you want to use it. Other than that this is not specifically a bug in PancakeView itself and the original bug is a Xamarin bug, so I will close this for now.
