### ISSUE TITLE
[Feature] Enhance the way the user defines borders

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Xamarin.Forms.PancakeView#93]
In line with shadows I would like to have borders be represented by a border object:

```
public class Border
{
   public Thickness Thickness { get; set; }
   public BorderDrawingStyle DrawingStyle { get; set; }
   public DashPattern DashPattern { get; set; }
   public Color Color { get; set; }
}
```

An additional markup extension can be made to make defining them in XAML easier.

**Comment by InquisitorJax** [comment]
@sthewissen would this facilitate acrylic style borders?
![image](https://user-images.githubusercontent.com/1822976/80596998-82245c00-8a27-11ea-8e9d-e2be3acc3753.png)

**Comment by sthewissen** [comment]
@InquisitorJax Not directly as shown in that sample. I'd use MaterialFrame for that. Abstracting it into a separate single `Border` object does slowly open the door for being able to draw multiple borders in the future. Not something that's on the planning just yet though.

**Comment by sthewissen** [comment]
@winnicki I haven't forgotten about your PR yet, slowly did the migration to a single Border object which is almost complete now on the vnext branch. One thing I was wondering, you added Edges and converted the border width into a Thickness. Aren't these similar in a way? If you want to hide a specific edge I could also just set that edge's Thickness to 0. Is there a scenario you had in mind where having both would make a difference?

**Comment by winnicki** [comment]
@sthewissen Good point, `Thickness` should be all that's needed.

**Comment by sthewissen** [comment]
Not happening anymore from my side, but happily taking PRs for it if the need is there.
