### ISSUE TITLE
Fontawesome is not working inside a PancakeView

### ISSUE THREAD

**Issue by erossini** [sthewissen/Xamarin.Forms.PancakeView#95]
In my app, I put the fonts in the main project and export the fonts from the AssemblyInfo.cs like:

    [assembly: ExportFont("FontAwesome5BrandsRegular.otf", Alias = "FontAwesomeBrands")]
    [assembly: ExportFont("FontAwesome5Solid.otf", Alias = "FontAwesomeSolid")]
    [assembly: ExportFont("FontAwesome5Regular.otf", Alias = "FontAwesomeRegular")]

    [assembly: ExportFont("InterMedium.ttf", Alias = "InterMedium")]

All fonts are working. I'm facing an issue only with FontAwesome in iOS. What I see on the iOS app is:

![image](https://user-images.githubusercontent.com/9497415/80430147-b98aef80-88e5-11ea-8d0d-2bc551a74406.png)

but in Android is working fine.

![image](https://user-images.githubusercontent.com/9497415/80430162-c4458480-88e5-11ea-8973-f881cb1095dd.png)

            <yummy:PancakeView Style="{StaticResource listOptionLayoutStyle}"
                               HorizontalOptions="EndAndExpand"
                               CornerRadius="5, 0, 5 ,0">
                <yummy:PancakeView.Triggers>
                    <DataTrigger TargetType="yummy:PancakeView"
                                 Binding="{Binding ListLayout}"
                                 Value="{x:Static models:ListLayoutOptions.Big}">
                        <Setter Property="BackgroundColor"
                                Value="{StaticResource primaryColor}"/>
                    </DataTrigger>
                </yummy:PancakeView.Triggers>
                <Label Text="{x:Static utils:FontAwesomeIcons.Envelope}"
                       Style="{StaticResource listOptionLayoutTextStyle}"
                       FontFamily="FontAwesomeSolid">
                    <Label.Triggers>
                        <DataTrigger TargetType="Label"
                                     Binding="{Binding ListLayout}"
                                     Value="{x:Static models:ListLayoutOptions.Big}">
                            <Setter Property="TextColor"
                                    Value="{DynamicResource background }"/>
                        </DataTrigger>
                    </Label.Triggers>
                    <Label.GestureRecognizers>
                        <TapGestureRecognizer Command="{Binding ChangeLayoutCommand}"
                                CommandParameter="{x:Static models:ListLayoutOptions.Big}"/>
                    </Label.GestureRecognizers>
                </Label>
            </yummy:PancakeView>

In the some project in the home page I'm using _Fontawesome_ and it is working.

![image](https://user-images.githubusercontent.com/9497415/80430314-3027ed00-88e6-11ea-80c8-561b152f9b4e.png)

Do you have any idea why or how can I fix it? Thank you!

**Comment by sthewissen** [comment]
This is most likely related to a Xamarin.Forms issue when using Embedded fonts. If they become too small I've had them not work for me either, inside or outside PancakeViews. Try increasing the size to something like 28 for the ones that aren't working. If they render correctly then it's most likely an issue somewhere in that direction.
